06-deep-vue/01-Buttons
js-tasks-ru/vue-20200925-2_bochesan pull request #19
Opened 2020-12-18 14:38 UTC by Bochesan

2020-12-18 14:54 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Buttons
+ Компонент BaseButton должен иметь логический параметр block
+ Компонент BaseButton должен иметь необязательный строковый параметр tag со значением button по умолчанию
+ Параметр tag у BaseButton должен иметь валидатор
+ Компонент BaseButton должен рендерить своё содержимое
+ Компонент BaseButton должен иметь класс button_block только с параметром block
+ Компонент BaseButton должен рендерить ссылку с tag=a c переданными href и target
+ Компонент BaseButton должен обрабатывать нативный клик
+ Компонент PrimaryButton должен рендерить компонент BaseButton с теми же параметрами, обработчиками событий и содержимым
+ Компонент PrimaryButton должен рендерить кнопку с классом button_primary
+ Компонент SecondaryButton должен рендерить компонент BaseButton с теми же параметрами, обработчиками событий и содержимым
+ Компонент SecondaryButton должен рендерить кнопку с классом button_secondary
+ Компонент DangerButton должен рендерить компонент BaseButton с теми же параметрами, обработчиками событий и содержимым
+ Компонент DangerButton должен рендерить кнопку с классом button_danger
```

Добавляю преподавателя (@ShGKme) для код-ревью, посмотрим что он скажет :)

2020-12-18 21:42 UTC, ShGKme requested changes
Требуется небольшое исправление в BaseButton

2020-12-18 21:42 UTC, ShGKme commented on 06-deep-vue/01-Buttons/components/BaseButton.vue
> +  </component>
Здесь также требуется передавать параметрами все атрибуты. Хотя `<component>` здесь - это корневой элемент, и вроде бы все атрибуты должны наследоваться, но наследоваться будут только атрибуты (например, `href` на `<a>`), а не параметры на компоненты (например, `to` на `<router-link>`).

Пример: https://repl.it/@ShGKme/Vue-Inherit-Props

2020-12-18 21:45 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
DateInput
+ DateInput должен выводить левую иконку в AppInput через слот left-icon
- DateInput должен иметь параметры type, valueAsDate и valueAsNumber
- DateInput должен рендерить AppInput[type=date]
- DateInput должен рендерить AppInput[type=time]
- DateInput должен рендерить AppInput[type=datetime-local]
- DateInput[type=date] должен выводить поле ввода со значением в соответствии с valueAsDate в формате yyyy-mm-dd
- DateInput[type=time] должен выводить поле ввода со значением в соответствии с valueAsDate в формате hh:mm
- DateInput[type=datetime-local] должен выводить поле ввода со значением в соответствии с valueAsDate в формате yyyy-mm-ddThh:mm
- DateInput[type=date] должен выводить поле ввода со значением в соответствии с valueAsNumber в формате yyyy-mm-dd
- DateInput[type=time] должен выводить поле ввода со значением в соответствии с valueAsNumber в формате hh:mm
- DateInput[type=datetime-local] должен выводить поле ввода со значением в соответствии с valueAsNumber в формате yyyy-mm-ddThh:mm
- DateInput[type=time] должен выводить поле ввода со значением в соответствии с valueAsDate в формате hh:mm:ss, если атрибут step не кратен 60
- DateInput[type=date] должен выводить поле ввода со значением в соответствии valueAsNumber, если переданы и valueAsDate, и valueAsNumber, и value
- DateInput[type=date] должен выводить поле ввода со значением в соответствии value, если valueAsDate и valueAsNumber не переданы
- DateInput[type=date] должен синхронизировать параметры valueAsDate и valueAsNumber при вводе значения
- DateInput[type=datetime-local] должен синхронизировать параметры valueAsDate и valueAsNumber при вво��е значения
```
```diff
AppInput
+ AppInput должен иметь параметры small, rounded и multiline
+ AppInput должен рендерить поле ввода с классом form-control внутри блока input-group
+ AppInput должен иметь класс form-control_sm только с параметром small
+ AppInput должен иметь класс form-control_rounded только с параметром rounded
+ AppInput с параметром multiline должен рендерить многострочное поле ввода
+ Параметры small и rounded должны работать с многострочным AppInput
+ AppInput должен принимать различные атрибуты полей ввода
+ AppInput должен принимать различные атрибуты полей ввода для textarea
+ AppInput должен рендерить input type=(password)
+ AppInput должен рендерить input type=(num)
+ AppInput должен рендерить input type=(range)
+ AppInput должен рендерить input type=(date)
+ AppInput должен рендерить input type=(time)
+ AppInput должен рендер��ть input type=(email)
+ AppInput должен рендерить input type=(tel)
+ AppInput должен выводить текущее значение (multiline=false)
+ AppInput должен выводить текущее значение (multiline=true)
+ AppInput должен обрабатывать нативный ввод и порождать события input, change с введённым значением
+ AppInput должен выводить левую иконку и добавлять классы input-group_icon input-group_icon-left
+ AppInput должен выводить правую иконку и добавлять классы input-group_icon input-group_icon-right
```
```diff
Buttons
+ Компонент BaseButton должен иметь логический ��араметр block
+ Компонент BaseButton должен иметь необязательный строковый параметр tag со значением button по умолчанию
+ Параметр tag у BaseButton должен иметь валидатор
+ Компонент BaseButton должен рендерить своё содержимое
+ Компонент BaseButton должен иметь класс button_block только с параметром block
+ Компонент BaseButton должен рендерить ссылку с tag=a c переданными href и target
+ Компонент BaseButton должен обрабатывать нативный клик
+ Компонент PrimaryButton должен рендерить компонент BaseButton с теми же параметрами, обработчиками событий и содержимым
+ Компонент PrimaryButton должен рендерить кнопку с классом button_primary
+ Компонент SecondaryButton должен рендерить компонент BaseButton с теми же параметрами, обработчиками событий и содержимым
+ Компонент SecondaryButton должен рендерить кнопку с классом button_secondary
+ Компонент DangerButton должен рендерить компонент BaseButton с теми же параметрами, обработчиками событий и содержимым
+ Компонент DangerButton должен рендерить кнопку с классом button_danger
```

2020-12-18 21:52 UTC, ShGKme commented
В `<AppInput>` всё хорошо :)

2020-12-20 22:55 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2020-12-21 08:16 UTC, ShGKme approved these changes
Все задачи приняты, отлично 👍

2020-12-21 08:17 UTC, merged